---
- name: Node Exporter Run node_exporter container
  community.docker.docker_container:
    name: "{{ node_exporter_container_name }}"
    image: "{{ node_exporter_image }}:{{ node_exporter_version }}"
    container_default_behavior: compatibility
    command:
    - --path.rootfs=/host
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - "--web.listen-address=0.0.0.0:{{ node_exporter_port }}"
    - --collector.filesystem.fs-types-exclude="^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
    - --collector.filesystem.mount-points-exclude="^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+|var/lib/containers/storage/.+)($|/)"
    - --collector.wifi
    - --no-collector.infiniband
    # RAPL disabled due to more strict permissions for `/host/sys/class/powercap/intel-rapl:0/energy_uj` in newer kernels
    - --no-collector.rapl
    command_handling: correct
    state: started
    restart: "{{ node_exporter_container_restart }}"
    recreate: "{{ node_exporter_container_recreate }}"
    restart_policy: unless-stopped
    log_driver: journald
    log_options:
      tag: "{{ '{{' }}.Name{{ '}}' }}"
    network_mode: host
    pid_mode: host
    keep_volumes: no
    volumes:
    - /:/host:ro,rslave

- name: Node Exporter Configure firewalld
  ansible.posix.firewalld:
    port: "{{ node_exporter_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when: node_exporter_configure_firewalld
