---
dependency:
  name: galaxy
  options:
    role-file: test-requirements.yml
    requirements-file: test-requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
- name: fedora
  # List of dictionaries mapped to `config.vm.network`
  interfaces:
  # `network_name` is the required identifier, all other keys map to
  # arguments.
  - network_name: private_network
    ip: 192.168.200.50
  box: fedora/34-cloud-base
  memory: 1024
  cpus: 1
provisioner:
  name: ansible
  log: True
  options:
    v: True
  config_options:
    defaults:
      callback_enabled: profile_tasks
      force_color: true
verifier:
  name: ansible
